# Generated by Django 6.0.5 on 2026-06-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hospital', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('timing', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='doctors/')),
            ],
        ),
    ]
