# Generated by Django 6.0.5 on 2026-06-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='address',
            field=models.CharField(default='Not Available'),
            preserve_default=False,
        ),
    ]
