# Generated by Django 6.0.5 on 2026-06-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_doctor_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='address',
            field=models.TextField(default=''),
        ),
    ]
