# Generated by Django 6.0.5 on 2026-06-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_doctor_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Petionts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('disease', models.CharField(max_length=100)),
            ],
        ),
    ]
