# Generated by Django 6.0.5 on 2026-06-09 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_petionts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Petionts',
            new_name='Patient',
        ),
    ]
