# Generated by Django 6.0.5 on 2026-06-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_petionts_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='products/')),
                ('solution', models.TextField()),
                ('cname', models.CharField(max_length=100)),
                ('cimg', models.ImageField(upload_to='company/')),
                ('cprice', models.IntegerField()),
            ],
        ),
    ]
