# Generated by Django 6.0.5 on 2026-06-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Information',
            field=models.TextField(default='No information'),
        ),
    ]
