# Generated by Django 6.0.5 on 2026-06-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_products_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='body_part',
            field=models.CharField(default='chest', max_length=20),
        ),
    ]
