# Generated by Django 6.0.5 on 2026-06-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_products_body_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='cimg',
        ),
        migrations.RemoveField(
            model_name='products',
            name='cname',
        ),
        migrations.RemoveField(
            model_name='products',
            name='cprice',
        ),
        migrations.AlterField(
            model_name='products',
            name='Information',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='body_part',
            field=models.CharField(choices=[('head', 'Head'), ('chest', 'Chest'), ('legs', 'Legs')], max_length=20),
        ),
    ]
