# Generated by Django 6.0.5 on 2026-06-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_products_cimg_remove_products_cname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='cimg',
            field=models.ImageField(blank=True, null=True, upload_to='capsules/'),
        ),
        migrations.AddField(
            model_name='products',
            name='cname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='cprice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
