# Generated by Django 6.0.5 on 2026-06-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_products_cimg_products_cname_products_cprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='products/')),
                ('solution', models.TextField()),
                ('Information', models.TextField()),
                ('body_part', models.CharField(choices=[('head', 'Head'), ('chest', 'Chest'), ('legs', 'Legs')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
