# Generated by Django 6.0.5 on 2026-08-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_problems_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('car_capacity', models.IntegerField()),
                ('selected_places', models.TextField()),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('estimated_km', models.FloatField(default=0.0)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('problem', models.TextField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
