# Generated by Django 6.0.5 on 2026-08-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_carbooking_problem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Rooms/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='Rooms/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='Rooms/')),
                ('Roomtype', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, default='')),
                ('hospital', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('timing', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
