# Generated by Django 6.0.5 on 2026-08-27 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_add_rooms_delete_doctor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Add_Rooms',
            new_name='add_rooms_view',
        ),
    ]
