# Generated by Django 6.0.5 on 2026-08-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_add_rooms_add_rooms_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('room_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='add_rooms_view',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='add_rooms_view',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='add_rooms_view',
            name='timing',
        ),
    ]
