# Generated by Django 6.0.5 on 2026-08-29 05:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_booking_room_remove_add_rooms_view_hospital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_room',
            name='checkin',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking_room',
            name='checkout',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
