# Generated by Django 6.0.5 on 2026-08-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_booking_room_checkin_booking_room_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='people',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
