# Generated by Django 6.0.5 on 2026-08-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_patient_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_room',
            name='room_type',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
