# Generated by Django 6.0.5 on 2026-08-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_booking_room_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='people',
        ),
        migrations.AddField(
            model_name='booking_room',
            name='people',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
