# Generated by Django 6.0.5 on 2026-08-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_patient_people_booking_room_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_room',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
