# Generated by Django 6.0.5 on 2026-08-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_booking_room_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_room',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
