# Generated by Django 6.0.5 on 2026-08-29 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_booking_room_reject_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_room',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app.add_rooms_view'),
        ),
    ]
