# Generated by Django 6.0.5 on 2026-08-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_booking_room_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_rooms_view',
            name='address',
        ),
        migrations.RemoveField(
            model_name='add_rooms_view',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='add_rooms_view',
            name='image3',
        ),
        migrations.AddField(
            model_name='add_rooms_view',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='add_rooms_view',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_rooms_view',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='add_rooms_view',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
    ]
