# Generated by Django 6.0.5 on 2026-08-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_add_rooms_view_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_rooms_view',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='add_rooms_view',
            name='name',
        ),
        migrations.RemoveField(
            model_name='add_rooms_view',
            name='price',
        ),
        migrations.AddField(
            model_name='add_rooms_view',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='add_rooms_view',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='Rooms/'),
        ),
        migrations.AddField(
            model_name='add_rooms_view',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='Rooms/'),
        ),
        migrations.AlterField(
            model_name='add_rooms_view',
            name='image',
            field=models.ImageField(upload_to='Rooms/'),
        ),
    ]
