# Generated by Django 6.0.5 on 2026-08-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_add_rooms_view_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_rooms_view',
            name='room_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
