# Generated by Django 6.0.5 on 2026-08-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_add_rooms_view_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_rooms_view',
            name='room_number',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
