# Generated by Django 6.0.5 on 2026-08-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_add_rooms_view_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_rooms_view',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
