# Generated by Django 6.0.5 on 2026-09-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Problems',
        ),
        migrations.AddField(
            model_name='add_rooms_view',
            name='facilities',
            field=models.TextField(blank=True, default=''),
        ),
    ]
