# Generated by Django 6.0.5 on 2026-09-05 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_delete_patient_delete_problems_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_rooms_view',
            name='address',
        ),
    ]
