# Generated by Django 6.1.1 on 2026-09-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_booking_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_room',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
