# Generated by Django 6.1.1 on 2026-09-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_booking_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem',
            field=models.TextField(max_length=200),
        ),
    ]
