# Generated by Django 6.1.1 on 2026-09-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_problem_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
