# Generated by Django 6.1.1 on 2026-09-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_carbooking_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='answer',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
